### ISSUE TITLE
'function' object has no attribute 'func_name'

### ISSUE THREAD

**Issue by lgalke** [lgalke/googlecl#3]
```bash
AttributeError: 'function' object has no attribute 'func_name'
```
Caused by atom library.

**Comment by lgalke** [comment]
Detailed traceback:

```bash
Traceback (most recent call last):
  File "/usr/bin/google", line 4, in <module>
    __import__('pkg_resources').run_script('google-cl==0.9.15.1', 'google')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.5/site-packages/google_cl-0.9.15.1-py3.5.egg/EGG-INFO/scripts/google", line 58, in <module>
    import googlecl.authenticate
  File "/usr/lib/python3.5/site-packages/google_cl-0.9.15.1-py3.5.egg/googlecl/authenticate.py", line 7, in <module>
    from gdata.photos.service import PhotosService
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gdata-2.0.18-py3.5.egg/gdata/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/lib/python3.5/site-packages/gdata-2.0.18-py3.5.egg/atom/__init__.py", line 133, in <module>
  File "/usr/lib/python3.5/site-packages/gdata-2.0.18-py3.5.egg/atom/__init__.py", line 97, in mark_deprecated
AttributeError: 'function' object has no attribute 'func_name'
```

**Comment by lgalke** [comment]
@vinitkumar Maybe you have an idea to solve this?

**Comment by vinitkumar** [comment]
@lgalke I didn't look much deeply into this. But looks like it is because gdata is not Python3 ready yet. 

https://github.com/google/gdata-python-client/issues/47

More details here:
https://github.com/google/gdata-python-client/issues/29

The fix appears to be this:

https://github.com/scipy/scipy/pull/194/commits/e60098c5ccc82ab2b12de3504192134dc7b03c6f
i.e. Changing from func_name to __name__ as func_name disappeared in Python3.

I suppose we might need to send a PR to the gdata-python-client with the fix or maintain a fork ourselves.

**Comment by lgalke** [comment]
People are suspecting that gdata is no longer maintained and start using
https://github.com/google/google-api-python-client instead. Switching to that library would presumably result in some big changes in googlecl, but would be probably cleaner on the long run.

**Comment by vinitkumar** [comment]
@lgalke I totally agree. Would definitely require more engineering effort for sure.
